channels:
  - conda-forge
dependencies:
  - psutil >= 5.4.8
  - py-cpuinfo >= 8.0.0
  - distro >= 1.6.0
  - numpy >= 1.21.5
  - h5py >= 3.6.0
  - pytables >= 3.6.1
  - zarr >= 2.10.3
  - matplotlib >= 3.5.1
  - ipympl >= 0.8.2
